### ISSUE TITLE
Serializer normalize method should accept type string

### ISSUE THREAD

**Issue by fotinakis** [eneuhauser/ember-json-api#5]
Small one for ya...

Normally, the `normalize` method accepts a string type, ie. I should be able to do:

``` JavaScript
serializer.normalize('user', data);
```

...but that receives an `undefined is not a function` because of `type.eachAttribute(function(key)` in the serializer.

So, right now I have to do this:

``` JavaScript
serializer.normalize(this.store.modelFor('user'), data);
```

**Comment by eneuhauser** [comment]
Something must have changed with the `RESTSerializer`. Neither this version nor the current version of the `normalize` method of `JsonApiSerializer` touches the `type` parameter.

**Comment by fotinakis** [comment]
Sorry, nevermind! I must have misread the code, it looks like the `normalize` method always expected the actual type and not a string.
